// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InstrumentsColumns holds the columns for the "instruments" table.
	InstrumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// InstrumentsTable holds the schema information for the "instruments" table.
	InstrumentsTable = &schema.Table{
		Name:       "instruments",
		Columns:    InstrumentsColumns,
		PrimaryKey: []*schema.Column{InstrumentsColumns[0]},
	}
	// InstrumentErrorsColumns holds the columns for the "instrument_errors" table.
	InstrumentErrorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "code", Type: field.TypeUint},
		{Name: "text", Type: field.TypeString},
		{Name: "occurred_at", Type: field.TypeTime},
		{Name: "instrument_id", Type: field.TypeUUID, Nullable: true},
	}
	// InstrumentErrorsTable holds the schema information for the "instrument_errors" table.
	InstrumentErrorsTable = &schema.Table{
		Name:       "instrument_errors",
		Columns:    InstrumentErrorsColumns,
		PrimaryKey: []*schema.Column{InstrumentErrorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "fk__instrument_errors_instrument_id__instruments_id",
				Columns:    []*schema.Column{InstrumentErrorsColumns[4]},
				RefColumns: []*schema.Column{InstrumentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InstrumentsTable,
		InstrumentErrorsTable,
	}
)

func init() {
	InstrumentErrorsTable.ForeignKeys[0].RefTable = InstrumentsTable
}
