// Code generated by entc, DO NOT EDIT.

package ent

import (
	"backend/ent/instrument"
	"backend/ent/instrumenterror"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// InstrumentErrorQuery is the builder for querying InstrumentError entities.
type InstrumentErrorQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.InstrumentError
	// eager-loading edges.
	withCheck *InstrumentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InstrumentErrorQuery builder.
func (ieq *InstrumentErrorQuery) Where(ps ...predicate.InstrumentError) *InstrumentErrorQuery {
	ieq.predicates = append(ieq.predicates, ps...)
	return ieq
}

// Limit adds a limit step to the query.
func (ieq *InstrumentErrorQuery) Limit(limit int) *InstrumentErrorQuery {
	ieq.limit = &limit
	return ieq
}

// Offset adds an offset step to the query.
func (ieq *InstrumentErrorQuery) Offset(offset int) *InstrumentErrorQuery {
	ieq.offset = &offset
	return ieq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ieq *InstrumentErrorQuery) Unique(unique bool) *InstrumentErrorQuery {
	ieq.unique = &unique
	return ieq
}

// Order adds an order step to the query.
func (ieq *InstrumentErrorQuery) Order(o ...OrderFunc) *InstrumentErrorQuery {
	ieq.order = append(ieq.order, o...)
	return ieq
}

// QueryCheck chains the current query on the "check" edge.
func (ieq *InstrumentErrorQuery) QueryCheck() *InstrumentQuery {
	query := &InstrumentQuery{config: ieq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ieq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ieq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instrumenterror.Table, instrumenterror.FieldID, selector),
			sqlgraph.To(instrument.Table, instrument.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, instrumenterror.CheckTable, instrumenterror.CheckColumn),
		)
		fromU = sqlgraph.SetNeighbors(ieq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first InstrumentError entity from the query.
// Returns a *NotFoundError when no InstrumentError was found.
func (ieq *InstrumentErrorQuery) First(ctx context.Context) (*InstrumentError, error) {
	nodes, err := ieq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{instrumenterror.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ieq *InstrumentErrorQuery) FirstX(ctx context.Context) *InstrumentError {
	node, err := ieq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InstrumentError ID from the query.
// Returns a *NotFoundError when no InstrumentError ID was found.
func (ieq *InstrumentErrorQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ieq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{instrumenterror.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ieq *InstrumentErrorQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ieq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InstrumentError entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one InstrumentError entity is not found.
// Returns a *NotFoundError when no InstrumentError entities are found.
func (ieq *InstrumentErrorQuery) Only(ctx context.Context) (*InstrumentError, error) {
	nodes, err := ieq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{instrumenterror.Label}
	default:
		return nil, &NotSingularError{instrumenterror.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ieq *InstrumentErrorQuery) OnlyX(ctx context.Context) *InstrumentError {
	node, err := ieq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InstrumentError ID in the query.
// Returns a *NotSingularError when exactly one InstrumentError ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ieq *InstrumentErrorQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ieq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = &NotSingularError{instrumenterror.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ieq *InstrumentErrorQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ieq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InstrumentErrors.
func (ieq *InstrumentErrorQuery) All(ctx context.Context) ([]*InstrumentError, error) {
	if err := ieq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ieq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ieq *InstrumentErrorQuery) AllX(ctx context.Context) []*InstrumentError {
	nodes, err := ieq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InstrumentError IDs.
func (ieq *InstrumentErrorQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := ieq.Select(instrumenterror.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ieq *InstrumentErrorQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ieq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ieq *InstrumentErrorQuery) Count(ctx context.Context) (int, error) {
	if err := ieq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ieq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ieq *InstrumentErrorQuery) CountX(ctx context.Context) int {
	count, err := ieq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ieq *InstrumentErrorQuery) Exist(ctx context.Context) (bool, error) {
	if err := ieq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ieq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ieq *InstrumentErrorQuery) ExistX(ctx context.Context) bool {
	exist, err := ieq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InstrumentErrorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ieq *InstrumentErrorQuery) Clone() *InstrumentErrorQuery {
	if ieq == nil {
		return nil
	}
	return &InstrumentErrorQuery{
		config:     ieq.config,
		limit:      ieq.limit,
		offset:     ieq.offset,
		order:      append([]OrderFunc{}, ieq.order...),
		predicates: append([]predicate.InstrumentError{}, ieq.predicates...),
		withCheck:  ieq.withCheck.Clone(),
		// clone intermediate query.
		sql:  ieq.sql.Clone(),
		path: ieq.path,
	}
}

// WithCheck tells the query-builder to eager-load the nodes that are connected to
// the "check" edge. The optional arguments are used to configure the query builder of the edge.
func (ieq *InstrumentErrorQuery) WithCheck(opts ...func(*InstrumentQuery)) *InstrumentErrorQuery {
	query := &InstrumentQuery{config: ieq.config}
	for _, opt := range opts {
		opt(query)
	}
	ieq.withCheck = query
	return ieq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InstrumentID uuid.UUID `json:"instrument_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InstrumentError.Query().
//		GroupBy(instrumenterror.FieldInstrumentID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ieq *InstrumentErrorQuery) GroupBy(field string, fields ...string) *InstrumentErrorGroupBy {
	group := &InstrumentErrorGroupBy{config: ieq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ieq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ieq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		InstrumentID uuid.UUID `json:"instrument_id,omitempty"`
//	}
//
//	client.InstrumentError.Query().
//		Select(instrumenterror.FieldInstrumentID).
//		Scan(ctx, &v)
//
func (ieq *InstrumentErrorQuery) Select(fields ...string) *InstrumentErrorSelect {
	ieq.fields = append(ieq.fields, fields...)
	return &InstrumentErrorSelect{InstrumentErrorQuery: ieq}
}

func (ieq *InstrumentErrorQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ieq.fields {
		if !instrumenterror.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ieq.path != nil {
		prev, err := ieq.path(ctx)
		if err != nil {
			return err
		}
		ieq.sql = prev
	}
	return nil
}

func (ieq *InstrumentErrorQuery) sqlAll(ctx context.Context) ([]*InstrumentError, error) {
	var (
		nodes       = []*InstrumentError{}
		_spec       = ieq.querySpec()
		loadedTypes = [1]bool{
			ieq.withCheck != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &InstrumentError{config: ieq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ieq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ieq.withCheck; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*InstrumentError)
		for i := range nodes {
			fk := nodes[i].InstrumentID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(instrument.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "instrument_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Check = n
			}
		}
	}

	return nodes, nil
}

func (ieq *InstrumentErrorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ieq.querySpec()
	return sqlgraph.CountNodes(ctx, ieq.driver, _spec)
}

func (ieq *InstrumentErrorQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ieq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ieq *InstrumentErrorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   instrumenterror.Table,
			Columns: instrumenterror.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: instrumenterror.FieldID,
			},
		},
		From:   ieq.sql,
		Unique: true,
	}
	if unique := ieq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ieq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instrumenterror.FieldID)
		for i := range fields {
			if fields[i] != instrumenterror.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ieq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ieq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ieq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ieq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ieq *InstrumentErrorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ieq.driver.Dialect())
	t1 := builder.Table(instrumenterror.Table)
	columns := ieq.fields
	if len(columns) == 0 {
		columns = instrumenterror.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ieq.sql != nil {
		selector = ieq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ieq.predicates {
		p(selector)
	}
	for _, p := range ieq.order {
		p(selector)
	}
	if offset := ieq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ieq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InstrumentErrorGroupBy is the group-by builder for InstrumentError entities.
type InstrumentErrorGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (iegb *InstrumentErrorGroupBy) Aggregate(fns ...AggregateFunc) *InstrumentErrorGroupBy {
	iegb.fns = append(iegb.fns, fns...)
	return iegb
}

// Scan applies the group-by query and scans the result into the given value.
func (iegb *InstrumentErrorGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := iegb.path(ctx)
	if err != nil {
		return err
	}
	iegb.sql = query
	return iegb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := iegb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (iegb *InstrumentErrorGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(iegb.fields) > 1 {
		return nil, errors.New("ent: InstrumentErrorGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := iegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) StringsX(ctx context.Context) []string {
	v, err := iegb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iegb *InstrumentErrorGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = iegb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = fmt.Errorf("ent: InstrumentErrorGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) StringX(ctx context.Context) string {
	v, err := iegb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (iegb *InstrumentErrorGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(iegb.fields) > 1 {
		return nil, errors.New("ent: InstrumentErrorGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := iegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) IntsX(ctx context.Context) []int {
	v, err := iegb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iegb *InstrumentErrorGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = iegb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = fmt.Errorf("ent: InstrumentErrorGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) IntX(ctx context.Context) int {
	v, err := iegb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (iegb *InstrumentErrorGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(iegb.fields) > 1 {
		return nil, errors.New("ent: InstrumentErrorGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := iegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := iegb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iegb *InstrumentErrorGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = iegb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = fmt.Errorf("ent: InstrumentErrorGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) Float64X(ctx context.Context) float64 {
	v, err := iegb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (iegb *InstrumentErrorGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(iegb.fields) > 1 {
		return nil, errors.New("ent: InstrumentErrorGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := iegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := iegb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iegb *InstrumentErrorGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = iegb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = fmt.Errorf("ent: InstrumentErrorGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (iegb *InstrumentErrorGroupBy) BoolX(ctx context.Context) bool {
	v, err := iegb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (iegb *InstrumentErrorGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range iegb.fields {
		if !instrumenterror.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := iegb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iegb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (iegb *InstrumentErrorGroupBy) sqlQuery() *sql.Selector {
	selector := iegb.sql.Select()
	aggregation := make([]string, 0, len(iegb.fns))
	for _, fn := range iegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(iegb.fields)+len(iegb.fns))
		for _, f := range iegb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(iegb.fields...)...)
}

// InstrumentErrorSelect is the builder for selecting fields of InstrumentError entities.
type InstrumentErrorSelect struct {
	*InstrumentErrorQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ies *InstrumentErrorSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ies.prepareQuery(ctx); err != nil {
		return err
	}
	ies.sql = ies.InstrumentErrorQuery.sqlQuery(ctx)
	return ies.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ies *InstrumentErrorSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ies.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ies *InstrumentErrorSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ies.fields) > 1 {
		return nil, errors.New("ent: InstrumentErrorSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ies.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ies *InstrumentErrorSelect) StringsX(ctx context.Context) []string {
	v, err := ies.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ies *InstrumentErrorSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ies.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = fmt.Errorf("ent: InstrumentErrorSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ies *InstrumentErrorSelect) StringX(ctx context.Context) string {
	v, err := ies.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ies *InstrumentErrorSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ies.fields) > 1 {
		return nil, errors.New("ent: InstrumentErrorSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ies.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ies *InstrumentErrorSelect) IntsX(ctx context.Context) []int {
	v, err := ies.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ies *InstrumentErrorSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ies.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = fmt.Errorf("ent: InstrumentErrorSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ies *InstrumentErrorSelect) IntX(ctx context.Context) int {
	v, err := ies.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ies *InstrumentErrorSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ies.fields) > 1 {
		return nil, errors.New("ent: InstrumentErrorSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ies.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ies *InstrumentErrorSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ies.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ies *InstrumentErrorSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ies.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = fmt.Errorf("ent: InstrumentErrorSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ies *InstrumentErrorSelect) Float64X(ctx context.Context) float64 {
	v, err := ies.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ies *InstrumentErrorSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ies.fields) > 1 {
		return nil, errors.New("ent: InstrumentErrorSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ies.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ies *InstrumentErrorSelect) BoolsX(ctx context.Context) []bool {
	v, err := ies.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ies *InstrumentErrorSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ies.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instrumenterror.Label}
	default:
		err = fmt.Errorf("ent: InstrumentErrorSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ies *InstrumentErrorSelect) BoolX(ctx context.Context) bool {
	v, err := ies.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ies *InstrumentErrorSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ies.sql.Query()
	if err := ies.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
