// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Instrument is the predicate function for instrument builders.
type Instrument func(*sql.Selector)

// InstrumentError is the predicate function for instrumenterror builders.
type InstrumentError func(*sql.Selector)
